services:
- postgresql
before_script:
- psql -c 'create database fit_test;' -U postgres
- bin/rails db:migrate RAILS_ENV=test
- bin/rails db:migrate RAILS_ENV=test
script:
- bundle exec rake rspec

language: ruby
rvm:
- 2.3.1